//! Settings store for persistent YAML-based settings.
//!
//! Stores user settings in `~/.bmad-manager/settings.yaml` for
//! human-readability and easy manual editing.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use thiserror::Error;

/// Errors that can occur during settings operations.
#[derive(Error, Debug)]
pub enum SettingsError {
    #[error("Failed to read settings file: {0}")]
    ReadError(String),

    #[error("Failed to write settings file: {0}")]
    WriteError(String),

    #[error("Failed to parse settings YAML: {0}")]
    ParseError(String),

    #[error("Settings directory not found")]
    NoDirError,
}

impl serde::Serialize for SettingsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(&self.to_string())
    }
}

/// Workflow style preference.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum WorkflowStyle {
    #[default]
    QuickFlow,
    FullBMM,
}

/// User profile settings.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UserSettings {
    pub name: String,
}

/// BMAD-specific settings.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct BmadSettings {
    pub default_workflow: WorkflowStyle,
}

/// Tool configuration settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolSettings {
    pub ide_command: String,
}

impl Default for ToolSettings {
    fn default() -> Self {
        Self {
            ide_command: "code .".to_string(),
        }
    }
}

/// Git-related settings (stub for future stories).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitSettings {
    pub branch_pattern: String,
    pub worktree_location: String,
}

impl Default for GitSettings {
    fn default() -> Self {
        Self {
            branch_pattern: "story/{story_id}-{slug}".to_string(),
            worktree_location: "sibling".to_string(),
        }
    }
}

/// UI settings (stub for future stories).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UiSettings {
    pub theme: String,
    pub show_agent_icons: bool,
}

impl Default for UiSettings {
    fn default() -> Self {
        Self {
            theme: "system".to_string(),
            show_agent_icons: true,
        }
    }
}

/// Global application settings stored in ~/.bmad-manager/settings.yaml
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct GlobalSettings {
    pub wizard_completed: bool,
    pub user: UserSettings,
    pub bmad: BmadSettings,
    pub tools: ToolSettings,
    #[serde(default)]
    pub git: GitSettings,
    #[serde(default)]
    pub ui: UiSettings,
}

/// Gets the path to the settings directory (~/.bmad-manager).
fn get_settings_dir() -> Result<PathBuf, SettingsError> {
    dirs::home_dir()
        .map(|home| home.join(".bmad-manager"))
        .ok_or(SettingsError::NoDirError)
}

/// Gets the path to the settings file (~/.bmad-manager/settings.yaml).
fn get_settings_path() -> Result<PathBuf, SettingsError> {
    get_settings_dir().map(|dir| dir.join("settings.yaml"))
}

/// Reads settings from the settings file.
/// Returns default settings if the file doesn't exist.
pub fn get_settings() -> Result<GlobalSettings, SettingsError> {
    let path = get_settings_path()?;

    if !path.exists() {
        return Ok(GlobalSettings::default());
    }

    let content =
        std::fs::read_to_string(&path).map_err(|e| SettingsError::ReadError(e.to_string()))?;

    serde_yaml::from_str(&content).map_err(|e| SettingsError::ParseError(e.to_string()))
}

/// Saves settings to the settings file.
/// Creates the settings directory if it doesn't exist.
pub fn save_settings(settings: &GlobalSettings) -> Result<(), SettingsError> {
    let dir = get_settings_dir()?;
    let path = get_settings_path()?;

    // Create directory if it doesn't exist
    if !dir.exists() {
        std::fs::create_dir_all(&dir).map_err(|e| SettingsError::WriteError(e.to_string()))?;
    }

    // Add a header comment to the YAML
    let yaml =
        serde_yaml::to_string(settings).map_err(|e| SettingsError::WriteError(e.to_string()))?;

    let content = format!(
        "# BMAD Manager Settings\n# Generated by First Run Wizard\n\n{}",
        yaml
    );

    std::fs::write(&path, content).map_err(|e| SettingsError::WriteError(e.to_string()))
}

/// Checks if the wizard has been completed.
pub fn is_wizard_completed() -> Result<bool, SettingsError> {
    let settings = get_settings()?;
    Ok(settings.wizard_completed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn setup_test_env() -> (TempDir, PathBuf) {
        let temp_dir = TempDir::new().unwrap();
        let settings_dir = temp_dir.path().join(".bmad-manager");
        fs::create_dir_all(&settings_dir).unwrap();
        (temp_dir, settings_dir.join("settings.yaml"))
    }

    #[test]
    fn test_default_settings() {
        let settings = GlobalSettings::default();
        assert!(!settings.wizard_completed);
        assert_eq!(settings.user.name, "");
        assert_eq!(settings.bmad.default_workflow, WorkflowStyle::QuickFlow);
        assert_eq!(settings.tools.ide_command, "code .");
    }

    #[test]
    fn test_settings_serialization() {
        let settings = GlobalSettings {
            wizard_completed: true,
            user: UserSettings {
                name: "TestUser".to_string(),
            },
            bmad: BmadSettings {
                default_workflow: WorkflowStyle::FullBMM,
            },
            tools: ToolSettings {
                ide_command: "cursor .".to_string(),
            },
            git: GitSettings::default(),
            ui: UiSettings::default(),
        };

        let yaml = serde_yaml::to_string(&settings).unwrap();
        assert!(yaml.contains("wizard_completed: true"));
        assert!(yaml.contains("name: TestUser"));
        assert!(yaml.contains("FullBMM"));
        assert!(yaml.contains("cursor ."));
    }

    #[test]
    fn test_settings_deserialization() {
        let yaml = r#"
wizard_completed: true
user:
  name: JohnDoe
bmad:
  default_workflow: QuickFlow
tools:
  ide_command: "code ."
"#;

        let settings: GlobalSettings = serde_yaml::from_str(yaml).unwrap();
        assert!(settings.wizard_completed);
        assert_eq!(settings.user.name, "JohnDoe");
        assert_eq!(settings.bmad.default_workflow, WorkflowStyle::QuickFlow);
        assert_eq!(settings.tools.ide_command, "code .");
    }

    #[test]
    fn test_workflow_style_serialization() {
        assert_eq!(
            serde_yaml::to_string(&WorkflowStyle::QuickFlow).unwrap().trim(),
            "QuickFlow"
        );
        assert_eq!(
            serde_yaml::to_string(&WorkflowStyle::FullBMM).unwrap().trim(),
            "FullBMM"
        );
    }

    #[test]
    fn test_get_settings_dir() {
        // This test just verifies the function doesn't panic
        // and returns a path containing .bmad-manager
        let result = get_settings_dir();
        assert!(result.is_ok());
        let path = result.unwrap();
        assert!(path.to_string_lossy().contains(".bmad-manager"));
    }
}
